/**
 * LBC Sunday Setlist
 * ──────────────────
 * Generated by scripts/prep from the approved rows of the setlist sheet.
 *
 * Sunday 2026-09-06
 */

window.WORSHIP_SETLIST = [
  'how-long-o-lord-how-long-psalm-13',
];
