/**
 * LBC Sunday Setlist
 * ──────────────────
 * Generated by scripts/prep from the approved rows of the setlist sheet.
 *
 * Sunday 2026-08-30
 */

window.WORSHIP_SETLIST = [
  'his-forever',
  'i-will-glory-in-my-redeemer',
  'i-asked-the-lord-that-i-might-grow',
];
